CREATE TABLE `CONTACT`(
    `CONTACT_ID` INT(2) NOT NULL AUTO_INCREMENT,
    `STR_NAME` VARCHAR(30),
    `CITY` VARCHAR(15) NOT NULL,
    `PHONE` VARCHAR(15) NOT NULL,
    CONSTRAINT CON_CONTACT_ID_PK PRIMARY KEY (CONTACT_ID)
) ENGINE = INNODB AUTO_INCREMENT = 10;

INSERT INTO CONTACT VALUES(NULL,'Str. Rozelor nr.9', 'Bucuresti', '0749322455');
INSERT INTO CONTACT VALUES(NULL,'Str. Decebal nr.12', 'Ploiesti', '0773911458');
INSERT INTO CONTACT VALUES(NULL,'Bld. Otilia Cazimir nr.1', 'Bucuresti', '0755412455');
INSERT INTO CONTACT VALUES(NULL,'Str. Sf. Lazar', 'Iasi', '0744953388');
INSERT INTO CONTACT VALUES(NULL,'Bld. Independentei', 'Alba Iulia', '0749322455');
INSERT INTO CONTACT VALUES(NULL,'Str. Zamfir nr.9', 'Buzau', '0723455833');
INSERT INTO CONTACT VALUES(NULL,'Str. Vasile Pogor nr1.10', 'Iasi', '0724999489');

CREATE TABLE `SUPPLIERS`(
    `SUPPLIER_ID` INT(3) NOT NULL AUTO_INCREMENT,
    `SUPPLIER_NAME` VARCHAR(40) NOT NULL,
    `CONTACT_ID` INT(2) UNIQUE NOT NULL,
    CONSTRAINT SUP_SUPPLIER_ID_PK PRIMARY KEY (SUPPLIER_ID),
    CONSTRAINT SUP_CONTACT_ID_FK FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID)
) ENGINE = INNODB AUTO_INCREMENT = 100;

INSERT INTO SUPPLIERS VALUES(NULL,'Coca Cola HBC', 10);
INSERT INTO SUPPLIERS VALUES(NULL,'Tomatoes RO', 11);
INSERT INTO SUPPLIERS VALUES(NULL,'Premium Drinks Romania', 12);
INSERT INTO SUPPLIERS VALUES(NULL,'Madrerom', 13);
INSERT INTO SUPPLIERS VALUES(NULL,'Gusto Romania', 14);
INSERT INTO SUPPLIERS VALUES(NULL,'Westhoeve Potatoes', 15);
INSERT INTO SUPPLIERS VALUES(NULL,'Melini Frutta', 16);

CREATE TABLE `CATEGORIES`(
    `CATEGORY_ID` INT(2) NOT NULL AUTO_INCREMENT,
    `CATEGORY_NAME` VARCHAR(15) NOT NULL,
    CONSTRAINT CAT_CATEGORY_ID_PK PRIMARY KEY (CATEGORY_ID)
) ENGINE = INNODB;

INSERT INTO CATEGORIES VALUES(NULL,'Legume');
INSERT INTO CATEGORIES VALUES(NULL,'Fructe');
INSERT INTO CATEGORIES VALUES(NULL,'Vinuri');
INSERT INTO CATEGORIES VALUES(NULL,'Bere');
INSERT INTO CATEGORIES VALUES(NULL,'Sucuri');
INSERT INTO CATEGORIES VALUES(NULL,'Pufuleti');
INSERT INTO CATEGORIES VALUES(NULL,'Ciocolata');
INSERT INTO CATEGORIES VALUES(NULL,'Lactate');
INSERT INTO CATEGORIES VALUES(NULL,'Peste');
INSERT INTO CATEGORIES VALUES(NULL,'Oua');
INSERT INTO CATEGORIES VALUES(NULL,'Carne');


CREATE TABLE `PRODUCTS`(
    `PRODUCT_ID` INT(6) NOT NULL,
    `PRODUCT_NAME` VARCHAR(35) NOT NULL,
    `CATEGORY_ID` INT(2) NOT NULL,
    `SUPPLIER_ID` INT(3) NOT NULL,
    `PRODUCT_PRICE` VARCHAR(11) NOT NULL,
    `STORAGE_DATE` DATE,
    CONSTRAINT P_PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID),
    CONSTRAINT P_PRODUCT_ID_CK CHECK (LENGTH(PRODUCT_ID) = 6),
    CONSTRAINT P_CATEGORY_ID_FK FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID),
    CONSTRAINT P_SUPPLIER_ID_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID)
) ENGINE = INNODB;

INSERT INTO PRODUCTS VALUES(100000,'Sprite 0.5L',5,100,CONCAT(FORMAT(3.55,2),' LEI'),'2018.02.11');
INSERT INTO PRODUCTS VALUES(100001,'Coca.Cola 0.5L',5,100,CONCAT(FORMAT(3.45,2),' LEI'),'2018.02.11');
INSERT INTO PRODUCTS VALUES(100002,'Sprite 0.5L',5,100,CONCAT(FORMAT(3.55,2),' LEI'),'2018.02.11');
INSERT INTO PRODUCTS VALUES(100003,'Rosii cherry',1,101,CONCAT(FORMAT(2.49,2),' LEI'),'2018.02.21');
INSERT INTO PRODUCTS VALUES(100004,'Busuioaca de Bohotin',3,102,CONCAT(FORMAT(13.09,2),' LEI'),'2018.03.13');
INSERT INTO PRODUCTS VALUES(100005,'Banane',2,103,CONCAT(FORMAT(5.69,2),' LEI'),'2018.03.25');
INSERT INTO PRODUCTS VALUES(100006,'Gusto',6,104,CONCAT(FORMAT(1.99,2),' LEI'),'2018.04.12');
INSERT INTO PRODUCTS VALUES(100007,'Cartofi albi',1,105,CONCAT(FORMAT(1.50,2),' LEI'),'2018.04.08');
INSERT INTO PRODUCTS VALUES(100008,'Cartofi rosii',1,105,CONCAT(FORMAT(1.55,2),' LEI'),'2018.04.08');
INSERT INTO PRODUCTS VALUES(100009,'Mere rosii',2,106,CONCAT(FORMAT(2.50,2),' LEI'),'2018.04.09');
INSERT INTO PRODUCTS VALUES(100010,'Mere golden',2,106,CONCAT(FORMAT(3.55,2),' LEI'),'2018.04.09');
